name: Main

on:
  push:
    branches: 
      - 'main'
    paths-ignore: 
      - '.github/workflows'
  workflow_dispatch:
    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - run: echo "Hello World!"
